//

typedef enum {
    optype_undefined,
    optype_implied,
    optype_nop, // NOP / PAUSE
    optype_prefix,
    optype_string,
    optype_prefix66,
    optype_prefix67,
    optype_extend_0F,
    optype_extend_0F38,
    optype_extend_0F3A,

    optype_Zv,
    optype_Zb,
    optype_ZbIb,
    optype_ZvIv,

    optype_ALIb,
    optype_AXIz,
    optype_IbAL,
    optype_IbAX,
    optype_AXIb,

    optype_Ib,
    optype_Iw, // RET Iw
    optype_Iz,
    optype_Jb,
    optype_Jz,

    optype_Ap,
    optype_IwIb, // ENTER

    optype_ALOb, // MOV AL, Ob
    optype_AXOv, // MOV rAX, Ov
    optype_ObAL, // MOV Ob, AL
    optype_OvAX, // MOV Ov, rAX

    optype_modrm_   = 0x40000000,
    optype_simd     = 0x70000000,

    opa_Emask       = 0x00000003,
    opa_Eb          = 0x00000001,
    opa_Ew          = 0x00000002,
    opa_Ev          = 0x00000003,
    opa_Gmask       = 0x0000000C,
    opa_Gb          = 0x00000004,
    opa_Gw          = 0x00000008,
    opa_Gv          = 0x0000000C,
    opa_Imask       = 0x00000030,
    opa_Ib          = 0x00000010,
    opa_Iw          = 0x00000020,
    opa_Iz          = 0x00000030,
    opa_Omask       = 0x0000FF00,
    opa_M           = 0x00000100,
    opa_Sw          = 0x00000200,
    opa_RdCd        = 0x00000300,
    opa_RdDd        = 0x00000400,
    opa_group       = 0x01000000,
    opa_shift       = 0x02000000,
    opa_reverse     = 0x08000000,

    optype_fpu      = optype_modrm_,
    optype_group    = optype_modrm_ | opa_group,

    optype_EbGb     = optype_modrm_ | opa_Eb | opa_Gb,
    optype_EvGv     = optype_modrm_ | opa_Ev | opa_Gv,
    optype_GbEb     = optype_modrm_ | opa_Eb | opa_Gb | opa_reverse,
    optype_GvEv     = optype_modrm_ | opa_Ev | opa_Gv | opa_reverse,
    optype_GvEb     = optype_modrm_ | opa_Eb | opa_Gv | opa_reverse,
    optype_GvEw     = optype_modrm_ | opa_Ew | opa_Gv | opa_reverse,
    optype_Eb       = optype_modrm_ | opa_Eb,
    optype_Ev       = optype_modrm_ | opa_Ev,

    optype_EwGw     = optype_modrm_ | opa_Ew | opa_Gw,
    optype_GvM      = optype_modrm_ | opa_Gv | opa_M | opa_reverse,
    optype_M        = optype_modrm_ | opa_M,
    optype_Mp       = optype_modrm_ | opa_M,
    optype_EwSw     = optype_modrm_ | opa_Ew | opa_Sw,
    optype_SwEw     = optype_modrm_ | opa_Ew | opa_Sw | opa_reverse,

    optype_RdCd     = optype_modrm_ | opa_RdCd,
    optype_RdDd     = optype_modrm_ | opa_RdDd,
    optype_CdRd     = optype_modrm_ | opa_RdCd | opa_reverse,
    optype_DdRd     = optype_modrm_ | opa_RdDd | opa_reverse,

    optype_EvGvIb   = optype_modrm_ | opa_Ev | opa_Gv | opa_Ib,
    optype_EvGvIz   = optype_modrm_ | opa_Ev | opa_Gv | opa_Iz,
    optype_GvEvIb   = optype_modrm_ | opa_Ev | opa_Gv | opa_Ib | opa_reverse,
    optype_GvEvIz   = optype_modrm_ | opa_Ev | opa_Gv | opa_Iz | opa_reverse,
    optype_EbIb     = optype_modrm_ | opa_Eb | opa_Ib,
    optype_EvIv     = optype_modrm_ | opa_Ev | opa_Iz,
    optype_EvIbs    = optype_modrm_ | opa_Ev | opa_Ib,
    optype_EvIb     = optype_modrm_ | opa_Ev | opa_Ib,

    optype_shEbIb   = optype_modrm_ | opa_Eb | opa_Ib | opa_shift,
    optype_shEvIb   = optype_modrm_ | opa_Ev | opa_Ib | opa_shift,
    optype_shEb     = optype_modrm_ | opa_Eb | opa_shift,
    optype_shEv     = optype_modrm_ | opa_Ev | opa_shift,

} optype_t;

typedef enum {
    reg_type_al,
    reg_type_ax,
    reg_type_eax,
    reg_type_sreg,
    reg_type_creg,
    reg_type_dreg,
} disasm_reg_type;

const char *reg_names_AL[] = {"AL", "CL", "DL", "BL", "AH", "CH", "DH", "BH" };
const char *reg_names_AX[] = {"AX", "CX", "DX", "BX", "SP", "BP", "SI", "DI" };
const char *reg_names_EAX[] = {"EAX", "ECX", "EDX", "EBX", "ESP", "EBP", "ESI", "EDI" };
const char *reg_names_sreg[] = {"ES", "CS", "SS", "DS", "FS", "GS", "???", "???" };

enum {
    index_AX = 0,
    index_CX,
    index_DX,
    index_BX,
    index_SP,
    index_BP,
    index_SI,
    index_DI,
    index_EAX = 0,
    index_ECX,
    index_EDX,
    index_EBX,
    index_ESP,
    index_EBP,
    index_ESI,
    index_EDI,
    index_AL = 0,
    index_CL,
    index_DL,
    index_BL,
    index_AH,
    index_CH,
    index_DH,
    index_BH,
    index_ES = 0,
    index_CS,
    index_SS,
    index_DS,
    index_FS,
    index_GS,
};

typedef struct opmap_t {
    const char * name;
    const char * name32;
    optype_t optype;
    struct opmap_t *group;
    int n_oplands;
    const char *oplands1;
    const char *oplands2;
} opmap_t;

static opmap_t opcode_80[8] = {
    { "ADD", NULL, optype_EbIb },
    { "OR", NULL, optype_EbIb },
    { "ADC", NULL, optype_EbIb },
    { "SBB", NULL, optype_EbIb },
    { "AND", NULL, optype_EbIb },
    { "SUB", NULL, optype_EbIb },
    { "XOR", NULL, optype_EbIb },
    { "CMP", NULL, optype_EbIb },
};

static opmap_t opcode_81[8] = {
    { "ADD", NULL, optype_EvIv },
    { "OR", NULL, optype_EvIv },
    { "ADC", NULL, optype_EvIv },
    { "SBB", NULL, optype_EvIv },
    { "AND", NULL, optype_EvIv },
    { "SUB", NULL, optype_EvIv },
    { "XOR", NULL, optype_EvIv },
    { "CMP", NULL, optype_EvIv },
};

static opmap_t opcode_83[8] = {
    { "ADD", NULL, optype_EvIbs },
    { "OR", NULL, optype_EvIbs },
    { "ADC", NULL, optype_EvIbs },
    { "SBB", NULL, optype_EvIbs },
    { "AND", NULL, optype_EvIbs },
    { "SUB", NULL, optype_EvIbs },
    { "XOR", NULL, optype_EvIbs },
    { "CMP", NULL, optype_EvIbs },
};

static opmap_t opcode_8F[8] = {
    { "POP", NULL, optype_Ev },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
};

static opmap_t opcode_F6[8] = {
    { "TEST", NULL, optype_EbIb },
    { NULL, NULL, optype_undefined },
    { "NOT", NULL, optype_Eb },
    { "NEG", NULL, optype_Eb },
    { "MUL", NULL, optype_Eb },
    { "IMUL", NULL, optype_Eb },
    { "DIV", NULL, optype_Eb },
    { "IDIV", NULL, optype_Eb },
};

static opmap_t opcode_F7[8] = {
    { "TEST", NULL, optype_EvIv },
    { NULL, NULL, optype_undefined },
    { "NOT", NULL, optype_Ev },
    { "NEG", NULL, optype_Ev },
    { "MUL", NULL, optype_Ev },
    { "IMUL", NULL, optype_Ev },
    { "DIV", NULL, optype_Ev },
    { "IDIV", NULL, optype_Ev },
};

static opmap_t opcode_FE[8] = {
    { "INC", NULL, optype_Eb },
    { "DEC", NULL, optype_Eb },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
};

static opmap_t opcode_FF[8] = {
    { "INC", NULL, optype_Ev },
    { "DEC", NULL, optype_Ev },
    { "CALL", NULL, optype_Ev },
    { "CALLF", NULL, optype_Mp },
    { "JMP", NULL, optype_Ev },
    { "JMPF", NULL, optype_Mp },
    { "PUSH", NULL, optype_Ev },
    { NULL, NULL, optype_undefined },
};


static opmap_t opcode_0F00[8] = {
    { "SLDT", NULL, optype_Ev },
    { "STR", NULL, optype_Ev },
    { "LLDT", NULL, optype_Ev },
    { "LTR", NULL, optype_Ev },
    { "VERR", NULL, optype_Ev },
    { "VERW", NULL, optype_Ev },
    { "JMPE", NULL, optype_implied },
    { NULL, NULL, optype_undefined },
};

static opmap_t opcode_0F01[8] = {
    { "SGDT", NULL, optype_M },
    { "SIDT", NULL, optype_M },
    { "LGDT", NULL, optype_M },
    { "LIDT", NULL, optype_M },
    { "SMSW", NULL, optype_Ev },
    { NULL, NULL, optype_undefined },
    { "LMSW", NULL, optype_Ev },
    { "INVLPG", NULL, optype_M },
};

static opmap_t opcode_0FAE[8] = {
    { "FXSAVE", NULL, optype_M },
    { "FXRSTOR", NULL, optype_M },
    { "LDMXCSR", NULL, optype_Ev },
    { "STMXCSR", NULL, optype_Ev },
    { "XSAVE", NULL, optype_M },
    { "XRSTOR", NULL, optype_M },
    { NULL, NULL, optype_undefined },
    { "CLFLUSH", NULL, optype_M },
};

static opmap_t opcode_0FBA[8] = {
    { "BT", NULL, optype_EvIb },
    { "BTS", NULL, optype_EvIb },
    { "BTR", NULL, optype_EvIb },
    { "BTC", NULL, optype_EvIb },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
};

const char *shift_names[8] = {"ROL", "ROR", "RCL", "RCR", "SHL", "SHR", NULL, "SAR" };

opmap_t opcode1[256] = {
    { "ADD", NULL, optype_EbGb },
    { "ADD", NULL, optype_EvGv },
    { "ADD", NULL, optype_GbEb },
    { "ADD", NULL, optype_GvEv },
    { "ADD", NULL, optype_ALIb },
    { "ADD", NULL, optype_AXIz },
    { "PUSH", NULL, optype_implied, NULL, 1, "ES" },
    { "POP", NULL, optype_implied, NULL, 1, "ES" },
    { "OR", NULL, optype_EbGb },
    { "OR", NULL, optype_EvGv },
    { "OR", NULL, optype_GbEb },
    { "OR", NULL, optype_GvEv },
    { "OR", NULL, optype_ALIb },
    { "OR", NULL, optype_AXIz },
    { "PUSH", NULL, optype_implied, NULL, 1, "CS" },
    { NULL, NULL, optype_extend_0F },
    { "ADC", NULL, optype_EbGb },
    { "ADC", NULL, optype_EvGv },
    { "ADC", NULL, optype_GbEb },
    { "ADC", NULL, optype_GvEv },
    { "ADC", NULL, optype_ALIb },
    { "ADC", NULL, optype_AXIz },
    { "PUSH", NULL, optype_implied, NULL, 1, "SS" },
    { "POP", NULL, optype_implied, NULL, 1, "SS" },
    { "SBB", NULL, optype_EbGb },
    { "SBB", NULL, optype_EvGv },
    { "SBB", NULL, optype_GbEb },
    { "SBB", NULL, optype_GvEv },
    { "SBB", NULL, optype_ALIb },
    { "SBB", NULL, optype_AXIz },
    { "PUSH", NULL, optype_implied, NULL, 1, "DS" },
    { "POP", NULL, optype_implied, NULL, 1, "DS" },
    { "AND", NULL, optype_EbGb },
    { "AND", NULL, optype_EvGv },
    { "AND", NULL, optype_GbEb },
    { "AND", NULL, optype_GvEv },
    { "AND", NULL, optype_ALIb },
    { "AND", NULL, optype_AXIz },
    { "ES:", NULL, optype_prefix },
    { "DAA", NULL, optype_implied },
    { "SUB", NULL, optype_EbGb },
    { "SUB", NULL, optype_EvGv },
    { "SUB", NULL, optype_GbEb },
    { "SUB", NULL, optype_GvEv },
    { "SUB", NULL, optype_ALIb },
    { "SUB", NULL, optype_AXIz },
    { "CS:", NULL, optype_prefix },
    { "DAS", NULL, optype_implied },
    { "XOR", NULL, optype_EbGb },
    { "XOR", NULL, optype_EvGv },
    { "XOR", NULL, optype_GbEb },
    { "XOR", NULL, optype_GvEv },
    { "XOR", NULL, optype_ALIb },
    { "XOR", NULL, optype_AXIz },
    { "SS:", NULL, optype_prefix },
    { "AAA", NULL, optype_implied },
    { "CMP", NULL, optype_EbGb },
    { "CMP", NULL, optype_EvGv },
    { "CMP", NULL, optype_GbEb },
    { "CMP", NULL, optype_GvEv },
    { "CMP", NULL, optype_ALIb },
    { "CMP", NULL, optype_AXIz },
    { "DS:", NULL, optype_prefix },
    { "AAS", NULL, optype_implied },
    { "INC", NULL, optype_Zv },
    { "INC", NULL, optype_Zv },
    { "INC", NULL, optype_Zv },
    { "INC", NULL, optype_Zv },
    { "INC", NULL, optype_Zv },
    { "INC", NULL, optype_Zv },
    { "INC", NULL, optype_Zv },
    { "INC", NULL, optype_Zv },
    { "DEC", NULL, optype_Zv },
    { "DEC", NULL, optype_Zv },
    { "DEC", NULL, optype_Zv },
    { "DEC", NULL, optype_Zv },
    { "DEC", NULL, optype_Zv },
    { "DEC", NULL, optype_Zv },
    { "DEC", NULL, optype_Zv },
    { "DEC", NULL, optype_Zv },
    { "PUSH", NULL, optype_Zv },
    { "PUSH", NULL, optype_Zv },
    { "PUSH", NULL, optype_Zv },
    { "PUSH", NULL, optype_Zv },
    { "PUSH", NULL, optype_Zv },
    { "PUSH", NULL, optype_Zv },
    { "PUSH", NULL, optype_Zv },
    { "PUSH", NULL, optype_Zv },
    { "POP", NULL, optype_Zv },
    { "POP", NULL, optype_Zv },
    { "POP", NULL, optype_Zv },
    { "POP", NULL, optype_Zv },
    { "POP", NULL, optype_Zv },
    { "POP", NULL, optype_Zv },
    { "POP", NULL, optype_Zv },
    { "POP", NULL, optype_Zv },
    { "PUSHA", "PUSHAD", optype_implied },
    { "POPA", "POPAD", optype_implied },
    { "BOUNDS", NULL, optype_GvM },
    { "ARPL", NULL, optype_EwGw },
    { "FS:", NULL, optype_prefix },
    { "GS:", NULL, optype_prefix },
    { NULL, NULL, optype_prefix66 },
    { NULL, NULL, optype_prefix67 },
    { "PUSH", NULL, optype_Iz },
    { "IMUL", NULL, optype_GvEvIz },
    { "PUSH", NULL, optype_Ib },
    { "IMUL", NULL, optype_GvEvIb },
    { "INSB", NULL, optype_string },
    { "INSW", "INSD", optype_string },
    { "OUTSB", NULL, optype_string },
    { "OUTSW", "OUTSD", optype_string },
    { "JO", NULL, optype_Jb },
    { "JNO", NULL, optype_Jb },
    { "JB", NULL, optype_Jb },
    { "JNB", NULL, optype_Jb },
    { "JZ", NULL, optype_Jb },
    { "JNZ", NULL, optype_Jb },
    { "JNA", NULL, optype_Jb },
    { "JA", NULL, optype_Jb },
    { "JS", NULL, optype_Jb },
    { "JNS", NULL, optype_Jb },
    { "JP", NULL, optype_Jb },
    { "JNP", NULL, optype_Jb },
    { "JL", NULL, optype_Jb },
    { "JNL", NULL, optype_Jb },
    { "JNG", NULL, optype_Jb },
    { "JG", NULL, optype_Jb },
    { NULL, NULL, optype_group, opcode_80 },
    { NULL, NULL, optype_group, opcode_81 },
    { NULL, NULL, optype_group, opcode_80 },
    { NULL, NULL, optype_group, opcode_83 },
    { "TEST", NULL, optype_GbEb },
    { "TEST", NULL, optype_GvEv },
    { "XCHG", NULL, optype_GbEb },
    { "XCHG", NULL, optype_GvEv },
    { "MOV", NULL, optype_EbGb },
    { "MOV", NULL, optype_EvGv },
    { "MOV", NULL, optype_GbEb },
    { "MOV", NULL, optype_GvEv },
    { "MOV", NULL, optype_EwSw },
    { "LEA", NULL, optype_GvM },
    { "MOV", NULL, optype_SwEw },
    { NULL, NULL, optype_group, opcode_8F },
    { "NOP", NULL, optype_nop },
    { "XCHG", NULL, optype_Zv, NULL, 1, "AX" },
    { "XCHG", NULL, optype_Zv, NULL, 1, "AX" },
    { "XCHG", NULL, optype_Zv, NULL, 1, "AX" },
    { "XCHG", NULL, optype_Zv, NULL, 1, "AX" },
    { "XCHG", NULL, optype_Zv, NULL, 1, "AX" },
    { "XCHG", NULL, optype_Zv, NULL, 1, "AX" },
    { "XCHG", NULL, optype_Zv, NULL, 1, "AX" },
    { "CBW", "CWDE", optype_implied },
    { "CWD", "CDQ", optype_implied },
    { "CALL", NULL, optype_Ap },
    { "FWAIT", NULL, optype_implied },
    { "PUSHF", "PUSHFD", optype_implied },
    { "POPF", "POPFD", optype_implied },
    { "SAHF", NULL, optype_implied },
    { "LAHF", NULL, optype_implied },
    { "MOV", NULL, optype_ALOb },
    { "MOV", NULL, optype_AXOv },
    { "MOV", NULL, optype_ObAL },
    { "MOV", NULL, optype_OvAX },
    { "MOVSB", NULL, optype_string },
    { "MOVSW", "MOVSD", optype_string },
    { "CMPSB", NULL, optype_string },
    { "CMPSW", "CMPSD", optype_string },
    { "TEST", NULL, optype_ALIb },
    { "TEST", NULL, optype_AXIz },
    { "STOSB", NULL, optype_string },
    { "STOSW", "STOSD", optype_string },
    { "LODSB", NULL, optype_string },
    { "LODSW", "LODSD", optype_string },
    { "SCASB", NULL, optype_string },
    { "SCASW", "SCASD", optype_string },
    { "MOV", NULL, optype_ZbIb },
    { "MOV", NULL, optype_ZbIb },
    { "MOV", NULL, optype_ZbIb },
    { "MOV", NULL, optype_ZbIb },
    { "MOV", NULL, optype_ZbIb },
    { "MOV", NULL, optype_ZbIb },
    { "MOV", NULL, optype_ZbIb },
    { "MOV", NULL, optype_ZbIb },
    { "MOV", NULL, optype_ZvIv },
    { "MOV", NULL, optype_ZvIv },
    { "MOV", NULL, optype_ZvIv },
    { "MOV", NULL, optype_ZvIv },
    { "MOV", NULL, optype_ZvIv },
    { "MOV", NULL, optype_ZvIv },
    { "MOV", NULL, optype_ZvIv },
    { "MOV", NULL, optype_ZvIv },
    { NULL, NULL, optype_shEbIb, },
    { NULL, NULL, optype_shEvIb, },
    { "RET", NULL, optype_Iw },
    { "RET", NULL, optype_implied },
    { "LES", NULL, optype_GvM },
    { "LDS", NULL, optype_GvM },
    { "MOV", NULL, optype_EbIb },
    { "MOV", NULL, optype_EvIv },
    { "ENTER", NULL, optype_IwIb },
    { "LEAVE", NULL, optype_implied },
    { "RETF", NULL, optype_Iw },
    { "RETF", NULL, optype_implied },
    { "INT3", NULL, optype_implied },
    { "INT", NULL, optype_Ib },
    { "INTO", NULL, optype_implied },
    { "IRET", "IRETD", optype_implied },
    { NULL, NULL, optype_shEb, NULL, 2, NULL, "1" },
    { NULL, NULL, optype_shEv, NULL, 2, NULL, "1" },
    { NULL, NULL, optype_shEb, NULL, 2, NULL, "CL" },
    { NULL, NULL, optype_shEv, NULL, 2, NULL, "CL" },
    { "AAM", NULL, optype_Ib },
    { "AAD", NULL, optype_Ib },
    { "SALC", NULL, optype_implied },
    { "XLAT", NULL, optype_implied },
    { NULL, NULL, optype_fpu },
    { NULL, NULL, optype_fpu },
    { NULL, NULL, optype_fpu },
    { NULL, NULL, optype_fpu },
    { NULL, NULL, optype_fpu },
    { NULL, NULL, optype_fpu },
    { NULL, NULL, optype_fpu },
    { NULL, NULL, optype_fpu },
    { "LOOPNZ", NULL, optype_Jb },
    { "LOOPZ", NULL, optype_Jb },
    { "LOOP", NULL, optype_Jb },
    { "JCXZ", "JECXZ", optype_Jb },
    { "IN", NULL, optype_ALIb },
    { "IN", NULL, optype_AXIb },
    { "OUT", NULL, optype_IbAL },
    { "OUT", NULL, optype_IbAX },
    { "CALL", NULL, optype_Jz },
    { "JMP", NULL, optype_Jz },
    { "JMP", NULL, optype_Ap },
    { "JMP", NULL, optype_Jb },
    { "IN", NULL, optype_implied, NULL, 3, "AL", "DX" },
    { "IN", NULL, optype_implied, NULL, 3, "AX", "DX" },
    { "OUT", NULL, optype_implied, NULL, 3, "DX", "AL" },
    { "OUT", NULL, optype_implied, NULL, 3, "DX", "AX" },
    { "LOCK", NULL, optype_prefix },
    { "ICEBP", NULL, optype_implied },
    { "REPZ", NULL, optype_prefix },
    { "REPNZ", NULL, optype_prefix },
    { "HLT", NULL, optype_implied },
    { "CMC", NULL, optype_implied },
    { NULL, NULL, optype_group, opcode_F6 },
    { NULL, NULL, optype_group, opcode_F7 },
    { "CLC", NULL, optype_implied },
    { "STC", NULL, optype_implied },
    { "CLI", NULL, optype_implied },
    { "STI", NULL, optype_implied },
    { "CLD", NULL, optype_implied },
    { "STD", NULL, optype_implied },
    { NULL, NULL, optype_group, opcode_FE },
    { NULL, NULL, optype_group, opcode_FF },
};

opmap_t opcode2[256] = {
    { NULL, NULL, optype_group, opcode_0F00 },
    { NULL, NULL, optype_group, opcode_0F01 },
    { "LAR", NULL, optype_GvM },
    { "LSL", NULL, optype_GvM },
    { NULL, NULL, optype_undefined },
    { "LOADALL286", NULL, optype_implied },
    { "CLTS", NULL, optype_implied },
    { "LOADALL386", NULL, optype_implied },
    { "INVD", NULL, optype_implied },
    { "WBINVD", NULL, optype_implied },
    { NULL, NULL, optype_undefined },
    { "UD2", NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { "NOP", NULL, optype_Ev },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },

    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },

    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },

    { "MOV", NULL, optype_RdCd },
    { "MOV", NULL, optype_RdDd },
    { "MOV", NULL, optype_CdRd },
    { "MOV", NULL, optype_DdRd },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },

    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },

    { "WRMSR", NULL, optype_implied },
    { "RDTSC", NULL, optype_implied },
    { "RDMSR", NULL, optype_implied },
    { "RDPMC", NULL, optype_implied },
    { "SYSENTER", NULL, optype_implied },
    { "SYSEXIT", NULL, optype_implied },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },

    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },

    { "CMOVO", NULL, optype_GvEv },
    { "CMOVNO", NULL, optype_GvEv },
    { "CMOVC", NULL, optype_GvEv },
    { "CMOVNC", NULL, optype_GvEv },
    { "CMOVZ", NULL, optype_GvEv },
    { "CMOVNZ", NULL, optype_GvEv },
    { "CMOVNA", NULL, optype_GvEv },
    { "CMOVA", NULL, optype_GvEv },
    { "CMOVS", NULL, optype_GvEv },
    { "CMOVNS", NULL, optype_GvEv },
    { "CMOVPE", NULL, optype_GvEv },
    { "CMOVPO", NULL, optype_GvEv },
    { "CMOVL", NULL, optype_GvEv },
    { "CMOVNL", NULL, optype_GvEv },
    { "CMOVNG", NULL, optype_GvEv },
    { "CMOVG", NULL, optype_GvEv },

    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },

    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },

    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },

    { "JO", NULL, optype_Jz },
    { "JNO", NULL, optype_Jz },
    { "JB", NULL, optype_Jz },
    { "JNB", NULL, optype_Jz },
    { "JZ", NULL, optype_Jz },
    { "JNZ", NULL, optype_Jz },
    { "JNA", NULL, optype_Jz },
    { "JA", NULL, optype_Jz },
    { "JS", NULL, optype_Jz },
    { "JNS", NULL, optype_Jz },
    { "JP", NULL, optype_Jz },
    { "JNP", NULL, optype_Jz },
    { "JL", NULL, optype_Jz },
    { "JNL", NULL, optype_Jz },
    { "JNG", NULL, optype_Jz },
    { "JG", NULL, optype_Jz },

    { "SETO", NULL, optype_Eb },
    { "SETNO", NULL, optype_Eb },
    { "SETB", NULL, optype_Eb },
    { "SETNB", NULL, optype_Eb },
    { "SETZ", NULL, optype_Eb },
    { "SETNZ", NULL, optype_Eb },
    { "SETNA", NULL, optype_Eb },
    { "SETA", NULL, optype_Eb },
    { "SETS", NULL, optype_Eb },
    { "SETNS", NULL, optype_Eb },
    { "SETP", NULL, optype_Eb },
    { "SETNP", NULL, optype_Eb },
    { "SETL", NULL, optype_Eb },
    { "SETNL", NULL, optype_Eb },
    { "SETNG", NULL, optype_Eb },
    { "SETG", NULL, optype_Eb },

    { "PUSH", NULL, optype_implied, NULL, 1, "FS" },
    { "POP", NULL, optype_implied, NULL, 1, "FS" },
    { "CPUID", NULL, optype_implied },
    { "BT", NULL, optype_EvGv },
    { "SHLD", NULL, optype_EvGvIb },
    { "SHLD", NULL, optype_EvGv, NULL, 2, "CL" },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },

    { "PUSH", NULL, optype_implied, NULL, 1, "GS" },
    { "POP", NULL, optype_implied, NULL, 1, "GS" },
    { "RSM", NULL, optype_implied },
    { "BTS", NULL, optype_EvGv },
    { "SHRD", NULL, optype_EvGvIb },
    { "SHRD", NULL, optype_EvGv, NULL, 1, "CL" },
    { NULL, NULL, optype_group, opcode_0FAE },
    { "IMUL", NULL, optype_GvEv },

    { "CMPXCHG", NULL, optype_EbGb, NULL, 1 , "AL" },
    { "CMPXCHG", NULL, optype_EvGv, NULL, 1 , "AX" },
    { "LSS", NULL, optype_GvM },
    { "BTR", NULL, optype_EvGv },
    { "LFS", NULL, optype_GvM },
    { "LGS", NULL, optype_GvM },
    { "MOVZX", NULL, optype_GvEb },
    { "MOVZX", NULL, optype_GvEw },

    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_undefined },
    { NULL, NULL, optype_group, opcode_0FBA },
    { "BTC", NULL, optype_EvGv },
    { "BSF", NULL, optype_GvEv },
    { "BSR", NULL, optype_GvEv },
    { "MOVSX", NULL, optype_GvEb },
    { "MOVSX", NULL, optype_GvEw },

    { "XADD", NULL, optype_EbGb },
    { "XADD", NULL, optype_EvGv },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },
    { NULL, NULL, optype_simd },

    { "BSWAP", NULL, optype_Zv },
    { "BSWAP", NULL, optype_Zv },
    { "BSWAP", NULL, optype_Zv },
    { "BSWAP", NULL, optype_Zv },
    { "BSWAP", NULL, optype_Zv },
    { "BSWAP", NULL, optype_Zv },
    { "BSWAP", NULL, optype_Zv },
    { "BSWAP", NULL, optype_Zv },

};
